### ISSUE TITLE
Jack- I have an issue with there being no issues

### ISSUE THREAD

**Issue by zoekurtzer** [jackwaterloo/pihole-setup#1]
Also why can't I just make a comment, why does there have to be an existing issue first?? Thanks for being my friend. But make more repositories or else.

**Comment by jackwaterloo** [comment]
I'm make more repositories public soon 😈. Thank you for logging this issue

**Comment by zoekurtzer** [comment]
I look forward logging more issues for your upcoming repositories! 🫡
